# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:15
    container_name: go-worksheet-db
    environment:
      POSTGRES_DB: goworksheetdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: go-worksheet-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_password
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: